#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

lscolor=$(vivid generate nord)
if [ ! -z "${lscolor}" ]; then
    export LS_COLORS=$lscolor
fi
PS1='[\u@\h \W]\$ '
PS1='${\u:\h}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '


export HOSTNAME=$(hostname)
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/sdks/flutter/bin

# set XDG directories and editor variables
export $(envsubst < $HOME/dotfiles/dot_env)

alias docker-container-clean='docker rm -v $(docker ps --filter status=exited -q)'


# BEGIN_KITTY_SHELL_INTEGRATION
if test -n "$KITTY_INSTALLATION_DIR" -a -e "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"; then source "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"; fi
# END_KITTY_SHELL_INTEGRATION

export SOPS_AGE_KEY_FILE="$HOME/.config/sops/age/keys.txt"

eval $(ssh-agent -s) > /dev/null


if [ -f ~/dotfiles/scripts/scripts_paths ]; then
    OLD_PATH=$PATH
    source ~/dotfiles/scripts/scripts_paths

    if (( ${#PATH} < ${#OLD_PATH} )); then
        echo "Something went wrong with the scripts_paths file. Reverting to Path before that"
        export PATH=$OLD_PATH
    fi
fi

export PATH=$PATH:$HOME/.cargo/bin

source "$HOME/.local/share/../bin/env"
source "$HOME/dotfiles/bash/functions"
source "$HOME/dotfiles/bash/aliases"


eval "$(starship init bash)"
eval "$(zoxide init bash)"
eval "$(direnv hook bash)"

